// ============================================================================
// Comprehensive Mock Data for Battery Thermal Management & Aging Intelligence
// Fully synchronized with backend schemas (23 PostgreSQL tables & views)
// ============================================================================

const hoursAgo = (h) => new Date(Date.now() - h * 3600e3).toISOString();
const daysAgo = (d) => new Date(Date.now() - d * 86400e3).toISOString();

export const manufacturers = [
  { manufacturer_id: 1, manufacturer_name: "CATL Automotive Energy", created_at: daysAgo(365) },
  { manufacturer_id: 2, manufacturer_name: "LG Energy Solution", created_at: daysAgo(365) },
  { manufacturer_id: 3, manufacturer_name: "Panasonic Energy", created_at: daysAgo(365) },
  { manufacturer_id: 4, manufacturer_name: "BYD FinDreams Battery", created_at: daysAgo(365) },
  { manufacturer_id: 5, manufacturer_name: "Samsung SDI", created_at: daysAgo(365) },
];

export const chemistries = [
  { chemistry_id: 1, chemistry_code: "NMC", chemistry_name: "Nickel Manganese Cobalt (811)" },
  { chemistry_id: 2, chemistry_code: "LFP", chemistry_name: "Lithium Iron Phosphate" },
  { chemistry_id: 3, chemistry_code: "NCA", chemistry_name: "Nickel Cobalt Aluminum Oxide" },
];

export const batteries = [
  {
    battery_id: 1,
    id: 1,
    serial_number: "CATL-NMC-2024-001",
    battery_type: "CATL EnerOne NMC-811",
    model: "CATL EnerOne NMC-811",
    manufacturer_id: 1,
    manufacturer_name: "CATL Automotive Energy",
    chemistry_id: 1,
    chemistry_code: "NMC",
    nominal_capacity_ah: 150.0,
    install_date: "2024-01-15",
    status: "ACTIVE",
    soh_pct: 94.5,
    temperature_c: 32.4,
    risk_level: "low",
    thermal_risk: "LOW",
    health_risk: "LOW",
    is_anomaly: false,
    open_alerts: 0,
    cycle_count: 320,
    internal_resistance_mohm: 1.25,
  },
  {
    battery_id: 2,
    id: 2,
    serial_number: "LG-NMC-2024-004",
    battery_type: "LG Chem Ultium NMC",
    model: "LG Chem Ultium NMC",
    manufacturer_id: 2,
    manufacturer_name: "LG Energy Solution",
    chemistry_id: 1,
    chemistry_code: "NMC",
    nominal_capacity_ah: 180.0,
    install_date: "2023-11-20",
    status: "ACTIVE",
    soh_pct: 78.2,
    temperature_c: 48.7,
    risk_level: "medium",
    thermal_risk: "MEDIUM",
    health_risk: "HIGH",
    is_anomaly: false,
    open_alerts: 1,
    cycle_count: 780,
    internal_resistance_mohm: 2.15,
  },
  {
    battery_id: 3,
    id: 3,
    serial_number: "PAN-NCA-2023-019",
    battery_type: "Panasonic 2170 NCA Pack",
    model: "Panasonic 2170 NCA Pack",
    manufacturer_id: 3,
    manufacturer_name: "Panasonic Energy",
    chemistry_id: 3,
    chemistry_code: "NCA",
    nominal_capacity_ah: 210.0,
    install_date: "2023-08-10",
    status: "WARNING",
    soh_pct: 66.4,
    temperature_c: 63.8,
    risk_level: "critical",
    thermal_risk: "CRITICAL",
    health_risk: "CRITICAL",
    is_anomaly: true,
    open_alerts: 2,
    cycle_count: 1120,
    internal_resistance_mohm: 3.42,
  },
  {
    battery_id: 4,
    id: 4,
    serial_number: "BYD-LFP-2024-082",
    battery_type: "BYD Blade LFP Pack",
    model: "BYD Blade LFP Pack",
    manufacturer_id: 4,
    manufacturer_name: "BYD FinDreams Battery",
    chemistry_id: 2,
    chemistry_code: "LFP",
    nominal_capacity_ah: 160.0,
    install_date: "2024-03-01",
    status: "ACTIVE",
    soh_pct: 97.1,
    temperature_c: 33.1,
    risk_level: "low",
    thermal_risk: "LOW",
    health_risk: "LOW",
    is_anomaly: false,
    open_alerts: 0,
    cycle_count: 190,
    internal_resistance_mohm: 1.10,
  },
  {
    battery_id: 5,
    id: 5,
    serial_number: "BYD-LFP-2023-044",
    battery_type: "BYD Blade LFP Commercial",
    model: "BYD Blade LFP Commercial",
    manufacturer_id: 4,
    manufacturer_name: "BYD FinDreams Battery",
    chemistry_id: 2,
    chemistry_code: "LFP",
    nominal_capacity_ah: 200.0,
    install_date: "2023-09-12",
    status: "ACTIVE",
    soh_pct: 88.5,
    temperature_c: 36.8,
    risk_level: "low",
    thermal_risk: "LOW",
    health_risk: "MEDIUM",
    is_anomaly: false,
    open_alerts: 0,
    cycle_count: 640,
    internal_resistance_mohm: 1.65,
  },
  {
    battery_id: 6,
    id: 6,
    serial_number: "SDI-NMC-2024-012",
    battery_type: "Samsung SDI Gen6 NMC",
    model: "Samsung SDI Gen6 NMC",
    manufacturer_id: 5,
    manufacturer_name: "Samsung SDI",
    chemistry_id: 1,
    chemistry_code: "NMC",
    nominal_capacity_ah: 175.0,
    install_date: "2023-12-05",
    status: "ACTIVE",
    soh_pct: 72.8,
    temperature_c: 53.4,
    risk_level: "high",
    thermal_risk: "HIGH",
    health_risk: "HIGH",
    is_anomaly: false,
    open_alerts: 1,
    cycle_count: 890,
    internal_resistance_mohm: 2.85,
  },
  {
    battery_id: 7,
    id: 7,
    serial_number: "CATL-LFP-2024-009",
    battery_type: "CATL Shenxing Fast-Charge LFP",
    model: "CATL Shenxing Fast-Charge LFP",
    manufacturer_id: 1,
    manufacturer_name: "CATL Automotive Energy",
    chemistry_id: 2,
    chemistry_code: "LFP",
    nominal_capacity_ah: 155.0,
    install_date: "2024-04-18",
    status: "ACTIVE",
    soh_pct: 98.6,
    temperature_c: 28.9,
    risk_level: "low",
    thermal_risk: "LOW",
    health_risk: "LOW",
    is_anomaly: false,
    open_alerts: 0,
    cycle_count: 95,
    internal_resistance_mohm: 0.98,
  },
  {
    battery_id: 8,
    id: 8,
    serial_number: "PAN-NCA-2023-005",
    battery_type: "Panasonic High-Power NCA",
    model: "Panasonic High-Power NCA",
    manufacturer_id: 3,
    manufacturer_name: "Panasonic Energy",
    chemistry_id: 3,
    chemistry_code: "NCA",
    nominal_capacity_ah: 195.0,
    install_date: "2023-05-14",
    status: "WARNING",
    soh_pct: 58.9,
    temperature_c: 59.2,
    risk_level: "high",
    thermal_risk: "HIGH",
    health_risk: "CRITICAL",
    is_anomaly: true,
    open_alerts: 2,
    cycle_count: 1280,
    internal_resistance_mohm: 3.88,
  },
  {
    battery_id: 9,
    id: 9,
    serial_number: "LG-NMC-2024-031",
    battery_type: "LG Chem Long-Range NMC",
    model: "LG Chem Long-Range NMC",
    manufacturer_id: 2,
    manufacturer_name: "LG Energy Solution",
    chemistry_id: 1,
    chemistry_code: "NMC",
    nominal_capacity_ah: 190.0,
    install_date: "2024-02-28",
    status: "ACTIVE",
    soh_pct: 85.3,
    temperature_c: 41.5,
    risk_level: "low",
    thermal_risk: "MEDIUM",
    health_risk: "MEDIUM",
    is_anomaly: false,
    open_alerts: 0,
    cycle_count: 510,
    internal_resistance_mohm: 1.78,
  },
  {
    battery_id: 10,
    id: 10,
    serial_number: "SDI-NMC-2024-022",
    battery_type: "Samsung SDI High-Energy NMC",
    model: "Samsung SDI High-Energy NMC",
    manufacturer_id: 5,
    manufacturer_name: "Samsung SDI",
    chemistry_id: 1,
    chemistry_code: "NMC",
    nominal_capacity_ah: 165.0,
    install_date: "2024-01-08",
    status: "ACTIVE",
    soh_pct: 79.4,
    temperature_c: 47.1,
    risk_level: "medium",
    thermal_risk: "MEDIUM",
    health_risk: "HIGH",
    is_anomaly: true,
    open_alerts: 1,
    cycle_count: 730,
    internal_resistance_mohm: 2.22,
  },
  {
    battery_id: 11,
    id: 11,
    serial_number: "BYD-LFP-2024-118",
    battery_type: "BYD Blade Gen2 LFP",
    model: "BYD Blade Gen2 LFP",
    manufacturer_id: 4,
    manufacturer_name: "BYD FinDreams Battery",
    chemistry_id: 2,
    chemistry_code: "LFP",
    nominal_capacity_ah: 210.0,
    install_date: "2024-05-10",
    status: "ACTIVE",
    soh_pct: 91.2,
    temperature_c: 32.8,
    risk_level: "low",
    thermal_risk: "LOW",
    health_risk: "LOW",
    is_anomaly: false,
    open_alerts: 0,
    cycle_count: 360,
    internal_resistance_mohm: 1.34,
  },
  {
    battery_id: 12,
    id: 12,
    serial_number: "CATL-NMC-2023-088",
    battery_type: "CATL Qilin Cell-to-Pack NMC",
    model: "CATL Qilin Cell-to-Pack NMC",
    manufacturer_id: 1,
    manufacturer_name: "CATL Automotive Energy",
    chemistry_id: 1,
    chemistry_code: "NMC",
    nominal_capacity_ah: 220.0,
    install_date: "2023-10-19",
    status: "ACTIVE",
    soh_pct: 71.0,
    temperature_c: 56.3,
    risk_level: "high",
    thermal_risk: "HIGH",
    health_risk: "HIGH",
    is_anomaly: false,
    open_alerts: 1,
    cycle_count: 980,
    internal_resistance_mohm: 3.12,
  },
];

// Sensors for each battery pack
export const getMockSensorsForBattery = (batteryId) => [
  { sensor_id: batteryId * 10 + 1, battery_id: batteryId, sensor_type: "TEMPERATURE", location: "Module 1 - Positive Terminal", is_active: true },
  { sensor_id: batteryId * 10 + 2, battery_id: batteryId, sensor_type: "TEMPERATURE", location: "Module 2 - Central Core", is_active: true },
  { sensor_id: batteryId * 10 + 3, battery_id: batteryId, sensor_type: "TEMPERATURE", location: "Module 3 - Negative Terminal", is_active: true },
  { sensor_id: batteryId * 10 + 4, battery_id: batteryId, sensor_type: "ELECTRICAL", location: "Main Pack Busbar", is_active: true },
  { sensor_id: batteryId * 10 + 5, battery_id: batteryId, sensor_type: "COOLANT_FLOW", location: "Micro-Channel Inlet Port", is_active: true },
];

// High-fidelity time series telemetry for a battery
export const getMockReadingsForBattery = (batteryId) => {
  const b = batteries.find((x) => x.battery_id === Number(batteryId)) || batteries[0];
  const count = 35;
  const isCrit = b.risk_level === "critical" || b.temperature_c >= 60;
  const baseTemp = isCrit ? b.temperature_c - 18 : b.temperature_c - 6;

  return Array.from({ length: count }, (_, i) => {
    const p = i / (count - 1);
    // Non-linear thermal rise curve for critical packs
    const curve = isCrit ? Math.pow(p, 2.5) : p;
    const tempRise = (b.temperature_c - baseTemp) * curve;
    const noise = Math.sin(i * 0.7 + batteryId) * 0.8;
    const temp = Math.round((baseTemp + tempRise + noise) * 10) / 10;

    // SOH slowly drifts down over history
    const sohDrift = Math.round((b.soh_pct + (count - 1 - i) * 0.08) * 10) / 10;
    const voltage = Math.round((395 - i * 0.4 + Math.sin(i) * 1.5) * 10) / 10;
    const current = Math.round((120 + Math.sin(i * 0.5) * 35) * 10) / 10;
    const coolantFlow = isCrit ? Math.max(4.2, 8.5 - p * 3.5) : 8.8 + Math.cos(i) * 0.5;

    // Neighbor sensors for spatial comparison
    const s1Temp = temp;
    const s2Temp = b.is_anomaly && i > count - 8 ? temp - 14.5 : Math.round((temp + (Math.sin(i) * 0.5)) * 10) / 10;
    const s3Temp = Math.round((temp - 0.9 + Math.cos(i) * 0.4) * 10) / 10;

    return {
      t: i,
      recorded_at: new Date(Date.now() - (count - 1 - i) * 60e3).toISOString(),
      temperature_c: temp,
      soh_pct: sohDrift,
      voltage_v: voltage,
      current_a: current,
      flow_rate_lpm: Math.round(coolantFlow * 10) / 10,
      sensor_1_temp: s1Temp,
      sensor_2_temp: s2Temp,
      sensor_3_temp: s3Temp,
      is_anomaly: b.is_anomaly && i >= count - 5,
    };
  });
};

// Aging curve dataset
export const getMockAgingForBattery = (batteryId) => {
  const b = batteries.find((x) => x.battery_id === Number(batteryId)) || batteries[0];
  const maxCycles = b.cycle_count || 500;
  const steps = 15;
  const records = [];

  for (let i = 0; i <= steps; i++) {
    const cycle = Math.round((maxCycles / steps) * i);
    // Non-linear capacity degradation (knee curve after 800 cycles)
    const factor = cycle / 1200;
    const capPct = Math.max(55, Math.round((100 - factor * 35 - Math.pow(factor, 3) * 12) * 10) / 10);
    const capAh = Math.round(((b.nominal_capacity_ah * capPct) / 100) * 10) / 10;
    const resMohm = Math.round((1.0 + factor * 2.6 + Math.pow(factor, 2) * 0.8) * 100) / 100;

    records.push({
      aging_id: i + 1,
      battery_id: b.battery_id,
      measured_at: daysAgo(Math.round((steps - i) * 20)),
      cycle_count: cycle,
      calendar_age_days: Math.round(cycle * 0.8),
      capacity_ah: capAh,
      internal_resistance_mohm: resMohm,
      soh_pct: capPct,
    });
  }
  return records;
};

// Digital Twin & CFD Simulation Mock
export const getMockDigitalTwin = (batteryId) => {
  const b = batteries.find((x) => x.battery_id === Number(batteryId)) || batteries[0];
  return {
    twin_id: 100 + Number(batteryId),
    battery_id: Number(batteryId),
    model_version: "v2.4-microchannel-fe",
    last_synced_at: hoursAgo(0.5),
    simulated_soh_pct: b.soh_pct ? b.soh_pct - 0.4 : 91.0,
    simulations: [
      {
        simulation_id: 301,
        twin_id: 100 + Number(batteryId),
        run_at: hoursAgo(1.2),
        flow_rate_lpm: 9.2,
        inlet_temp_c: 24.5,
        max_temp_c: b.temperature_c,
        avg_temp_c: Math.round((b.temperature_c - 4.5) * 10) / 10,
        pressure_drop_kpa: 14.8,
        cooling_efficiency_pct: 88.4,
      },
      {
        simulation_id: 300,
        twin_id: 100 + Number(batteryId),
        run_at: hoursAgo(24),
        flow_rate_lpm: 8.5,
        inlet_temp_c: 24.0,
        max_temp_c: b.temperature_c - 3.2,
        avg_temp_c: b.temperature_c - 7.0,
        pressure_drop_kpa: 13.9,
        cooling_efficiency_pct: 91.0,
      },
    ],
  };
};

export const alerts = [
  {
    alert_id: 1,
    id: 1,
    battery_id: 3,
    serial_number: "PAN-NCA-2023-019",
    priority_code: "CRITICAL",
    severity_level: 4,
    risk_type: "THERMAL",
    final_risk_level: "CRITICAL",
    message: "Severe thermal runaway hazard: Peak temp 63.8°C exceeded hard safety ceiling (60°C).",
    status: "OPEN",
    created_at: hoursAgo(0.25),
    acknowledged_at: null,
    recommendation: "Take vehicle out of service immediately; isolate pack and flush micro-channel coolant loop.",
  },
  {
    alert_id: 2,
    id: 2,
    battery_id: 8,
    serial_number: "PAN-NCA-2023-005",
    priority_code: "HIGH",
    severity_level: 3,
    risk_type: "HEALTH",
    final_risk_level: "HIGH",
    message: "Critical capacity degradation: SOH dropped to 58.9% with elevated internal resistance (3.88 mΩ).",
    status: "OPEN",
    created_at: hoursAgo(1.8),
    acknowledged_at: null,
    recommendation: "Schedule immediate bench capacity test and plan module replacement.",
  },
  {
    alert_id: 3,
    id: 3,
    battery_id: 6,
    serial_number: "SDI-NMC-2024-012",
    priority_code: "HIGH",
    severity_level: 3,
    risk_type: "THERMAL",
    final_risk_level: "HIGH",
    message: "Elevated core temperature: 53.4°C during fast-charge session exceeding warning threshold.",
    status: "OPEN",
    created_at: hoursAgo(3.5),
    acknowledged_at: null,
    recommendation: "Throttle DC fast-charge rate to 0.5C and verify coolant pump circulation.",
  },
  {
    alert_id: 4,
    id: 4,
    battery_id: 10,
    serial_number: "SDI-NMC-2024-022",
    priority_code: "MEDIUM",
    severity_level: 2,
    risk_type: "THERMAL",
    final_risk_level: "MEDIUM",
    message: "Spatial temperature divergence: Sensor 2 in Module 2 drifted +9.8°C above neighbor sensors.",
    status: "ACKNOWLEDGED",
    created_at: hoursAgo(8.0),
    acknowledged_at: hoursAgo(2.1),
    recommendation: "Inspect thermistor wiring and calibrate cell group 2 balancing circuit.",
  },
  {
    alert_id: 5,
    id: 5,
    battery_id: 2,
    serial_number: "LG-NMC-2024-004",
    priority_code: "MEDIUM",
    severity_level: 2,
    risk_type: "HEALTH",
    final_risk_level: "MEDIUM",
    message: "Accelerated resistance increase: Internal resistance rose +18% over last 100 cycles.",
    status: "CONFIRMED",
    created_at: hoursAgo(28.0),
    acknowledged_at: hoursAgo(22.0),
    recommendation: "Monitor impedance trends during next scheduled inspection.",
  },
  {
    alert_id: 6,
    id: 6,
    battery_id: 12,
    serial_number: "CATL-NMC-2023-088",
    priority_code: "MEDIUM",
    severity_level: 2,
    risk_type: "THERMAL",
    final_risk_level: "MEDIUM",
    message: "High ambient temperature warning during heavy load pull.",
    status: "FALSE_ALARM",
    created_at: hoursAgo(46.0),
    acknowledged_at: hoursAgo(40.0),
    recommendation: "Transient cabin heat soak; false alarm confirmed by telemetry replay.",
  },
];

export const predictions = [
  {
    prediction_id: 101,
    battery_id: 3,
    serial_number: "PAN-NCA-2023-019",
    risk_type: "THERMAL",
    model_name: "thermal_risk_classifier",
    predicted_label: "HIGH",
    confidence: 0.942,
    final_risk_level: "CRITICAL",
    rule_override: true,
    predicted_at: hoursAgo(0.3),
    notes: "PLACEHOLDER RULES | Hard safety override engaged: temperature 63.8°C >= 60.0°C forces CRITICAL",
  },
  {
    prediction_id: 102,
    battery_id: 3,
    serial_number: "PAN-NCA-2023-019",
    risk_type: "HEALTH",
    model_name: "health_risk_classifier",
    predicted_label: "CRITICAL",
    confidence: 0.915,
    final_risk_level: "CRITICAL",
    rule_override: false,
    predicted_at: hoursAgo(0.3),
    notes: "Capacity 66.4% below 70% threshold; end-of-life health risk confirmed.",
  },
  {
    prediction_id: 103,
    battery_id: 8,
    serial_number: "PAN-NCA-2023-005",
    risk_type: "THERMAL",
    model_name: "thermal_risk_classifier",
    predicted_label: "HIGH",
    confidence: 0.887,
    final_risk_level: "HIGH",
    rule_override: false,
    predicted_at: hoursAgo(1.9),
    notes: "Sustained temperature 59.2°C approaching safety limit.",
  },
  {
    prediction_id: 104,
    battery_id: 6,
    serial_number: "SDI-NMC-2024-012",
    risk_type: "THERMAL",
    model_name: "thermal_risk_classifier",
    predicted_label: "HIGH",
    confidence: 0.835,
    final_risk_level: "HIGH",
    rule_override: false,
    predicted_at: hoursAgo(3.6),
    notes: "High discharge temperature spike detected.",
  },
  {
    prediction_id: 105,
    battery_id: 2,
    serial_number: "LG-NMC-2024-004",
    risk_type: "HEALTH",
    model_name: "health_risk_classifier",
    predicted_label: "HIGH",
    confidence: 0.792,
    final_risk_level: "HIGH",
    rule_override: false,
    predicted_at: hoursAgo(6.0),
    notes: "SOH 78.2% within High Degradation bracket (70-80%).",
  },
  {
    prediction_id: 106,
    battery_id: 1,
    serial_number: "CATL-NMC-2024-001",
    risk_type: "THERMAL",
    model_name: "thermal_risk_classifier",
    predicted_label: "LOW",
    confidence: 0.968,
    final_risk_level: "LOW",
    rule_override: false,
    predicted_at: hoursAgo(12.0),
    notes: "Normal thermal operating envelope (32.4°C).",
  },
];

export const anomalies = [
  {
    anomaly_id: 201,
    sensor_id: 31,
    battery_id: 3,
    serial_number: "PAN-NCA-2023-019",
    location: "Module 1 - Positive Terminal",
    detected_at: hoursAgo(0.4),
    anomaly_type: "OUT_OF_RANGE",
    cause: "BATTERY_ISSUE",
    detection_method: "RULE",
    anomaly_score: 8.8,
    details: "63.8°C exceeded maximum allowed threshold (55.0°C for NCA chemistry). Neighbor sensors also elevated.",
  },
  {
    anomaly_id: 202,
    sensor_id: 82,
    battery_id: 8,
    serial_number: "PAN-NCA-2023-005",
    location: "Module 2 - Central Core",
    detected_at: hoursAgo(2.1),
    anomaly_type: "SUDDEN_SPIKE",
    cause: "BATTERY_ISSUE",
    detection_method: "RULE",
    anomaly_score: 11.4,
    details: "Changed +11.4°C in 3.2 min (47.8°C to 59.2°C). High thermal rate of rise.",
  },
  {
    anomaly_id: 203,
    sensor_id: 102,
    battery_id: 10,
    serial_number: "SDI-NMC-2024-022",
    location: "Module 2 - Central Core",
    detected_at: hoursAgo(8.2),
    anomaly_type: "SUDDEN_SPIKE",
    cause: "SENSOR_FAULT",
    detection_method: "RULE",
    anomaly_score: 14.2,
    details: "Sensor jumped +14.2°C in 1.8 min while neighbor sensors stayed at normal 33°C. Indicative of probe fault.",
  },
  {
    anomaly_id: 204,
    sensor_id: 61,
    battery_id: 6,
    serial_number: "SDI-NMC-2024-012",
    location: "Module 1 - Positive Terminal",
    detected_at: hoursAgo(14.0),
    anomaly_type: "DRIFT",
    cause: "UNDETERMINED",
    detection_method: "RULE",
    anomaly_score: 6.2,
    details: "Gradual positive temperature drift under constant current load.",
  },
];

export const recommendations = [
  {
    recommendation_id: 401,
    target_role: "FLEET_OPERATOR",
    battery_id: 3,
    serial_number: "PAN-NCA-2023-019",
    source_type: "RISK",
    risk_level: "CRITICAL",
    anomaly_type: null,
    cause: null,
    recommendation_text: "Take the vehicle out of service immediately until the battery and cooling pack have been physically inspected.",
    created_at: hoursAgo(0.3),
  },
  {
    recommendation_id: 402,
    target_role: "BMS_ENGINEER",
    battery_id: 3,
    serial_number: "PAN-NCA-2023-019",
    source_type: "RISK",
    risk_level: "CRITICAL",
    anomaly_type: null,
    cause: null,
    recommendation_text: "Review high-frequency cell logs, reduce charge/discharge current limits to 0A, and inspect micro-channel coolant flow.",
    created_at: hoursAgo(0.3),
  },
  {
    recommendation_id: 403,
    target_role: "SERVICE_TECHNICIAN",
    battery_id: 3,
    serial_number: "PAN-NCA-2023-019",
    source_type: "RISK",
    risk_level: "CRITICAL",
    anomaly_type: null,
    cause: null,
    recommendation_text: "Inspect battery pack enclosure and micro-channel coolant loop immediately for leaks or channel blockages.",
    created_at: hoursAgo(0.3),
  },
  {
    recommendation_id: 404,
    target_role: "SERVICE_TECHNICIAN",
    battery_id: 10,
    serial_number: "SDI-NMC-2024-022",
    source_type: "ANOMALY",
    risk_level: "MEDIUM",
    anomaly_type: "SUDDEN_SPIKE",
    cause: "SENSOR_FAULT",
    recommendation_text: "Inspect or replace sensor probe #102 in Module 2. Its readings disagree sharply with neighbor thermistors.",
    created_at: hoursAgo(8.1),
  },
  {
    recommendation_id: 405,
    target_role: "FLEET_OPERATOR",
    battery_id: 8,
    serial_number: "PAN-NCA-2023-005",
    source_type: "RISK",
    risk_level: "HIGH",
    anomaly_type: null,
    cause: null,
    recommendation_text: "Limit DC fast-charging on this unit and schedule pack replacement before winter route deployment.",
    created_at: hoursAgo(1.9),
  },
];

export const aiModels = [
  {
    model_id: 1,
    model_name: "thermal_risk_classifier",
    version: "v1",
    task_type: "RISK_CLASSIFICATION",
    algorithm: "RandomForestClassifier",
    risk_type: "THERMAL",
    trained_at: daysAgo(14),
    is_active: true,
    notes: "Trained on synthetic_threshold_rules_v1 with 200 estimators; balanced class weights.",
  },
  {
    model_id: 2,
    model_name: "health_risk_classifier",
    version: "v1",
    task_type: "RISK_CLASSIFICATION",
    algorithm: "RandomForestClassifier",
    risk_type: "HEALTH",
    trained_at: daysAgo(14),
    is_active: true,
    notes: "Trained on multi-chemistry aging records with capacity loss features.",
  },
];

export const modelPerformance = [
  {
    performance_id: 1,
    model_id: 1,
    model_name: "thermal_risk_classifier",
    version: "v1",
    evaluation_type: "TEST_SET",
    sample_count: 1000,
    accuracy: 0.942,
    macro_f1: 0.928,
    recall_high_critical: 0.985,
    evaluated_at: daysAgo(14),
    notes: "Held-out test set evaluation.",
  },
  {
    performance_id: 2,
    model_id: 1,
    model_name: "thermal_risk_classifier",
    version: "v1",
    evaluation_type: "LIVE_FEEDBACK",
    sample_count: 84,
    accuracy: 0.916,
    macro_f1: 0.902,
    recall_high_critical: 0.964,
    evaluated_at: hoursAgo(2),
    notes: "Computed against technician and operator ground-truth feedback.",
  },
  {
    performance_id: 3,
    model_id: 2,
    model_name: "health_risk_classifier",
    version: "v1",
    evaluation_type: "TEST_SET",
    sample_count: 1000,
    accuracy: 0.918,
    macro_f1: 0.895,
    recall_high_critical: 0.941,
    evaluated_at: daysAgo(14),
    notes: "Degradation baseline test set.",
  },
  {
    performance_id: 4,
    model_id: 2,
    model_name: "health_risk_classifier",
    version: "v1",
    evaluation_type: "LIVE_FEEDBACK",
    sample_count: 52,
    accuracy: 0.884,
    macro_f1: 0.871,
    recall_high_critical: 0.923,
    evaluated_at: hoursAgo(2),
    notes: "Validated against lab bench capacity measurements.",
  },
];

export const liveAccuracy = [
  {
    model_id: 1,
    model_name: "thermal_risk_classifier",
    risk_type: "THERMAL",
    feedback_count: 84,
    exact_matches: 77,
    accuracy: 91.6,
    underestimated: 2,
  },
  {
    model_id: 2,
    model_name: "health_risk_classifier",
    risk_type: "HEALTH",
    feedback_count: 52,
    exact_matches: 46,
    accuracy: 88.4,
    underestimated: 3,
  },
];

export const chemistryComparison = [
  {
    chemistry_code: "NMC",
    chemistry_name: "Nickel Manganese Cobalt (811)",
    battery_count: 6,
    avg_cycles: 685,
    avg_resistance_mohm: 2.21,
    avg_capacity_pct_of_nominal: 80.2,
    avg_peak_temp_c: 46.8,
    max_peak_temp_c: 56.3,
    thermal_stability: "Moderate",
    energy_density: "High (250 Wh/kg)",
  },
  {
    chemistry_code: "LFP",
    chemistry_name: "Lithium Iron Phosphate",
    battery_count: 4,
    avg_cycles: 346,
    avg_resistance_mohm: 1.27,
    avg_capacity_pct_of_nominal: 93.8,
    avg_peak_temp_c: 32.9,
    max_peak_temp_c: 36.8,
    thermal_stability: "Exceptional (>65°C safe)",
    energy_density: "Moderate (160 Wh/kg)",
  },
  {
    chemistry_code: "NCA",
    chemistry_name: "Nickel Cobalt Aluminum Oxide",
    battery_count: 2,
    avg_cycles: 1200,
    avg_resistance_mohm: 3.65,
    avg_capacity_pct_of_nominal: 62.6,
    avg_peak_temp_c: 61.5,
    max_peak_temp_c: 63.8,
    thermal_stability: "Low (<55°C limit)",
    energy_density: "Very High (270 Wh/kg)",
  },
];

export const manufacturerComparison = [
  {
    manufacturer_id: 1,
    manufacturer_name: "CATL Automotive Energy",
    battery_count: 3,
    avg_cycles: 465,
    avg_resistance_mohm: 1.78,
    avg_capacity_pct_of_nominal: 88.0,
  },
  {
    manufacturer_id: 2,
    manufacturer_name: "LG Energy Solution",
    battery_count: 2,
    avg_cycles: 645,
    avg_resistance_mohm: 1.96,
    avg_capacity_pct_of_nominal: 81.8,
  },
  {
    manufacturer_id: 3,
    manufacturer_name: "Panasonic Energy",
    battery_count: 2,
    avg_cycles: 1200,
    avg_resistance_mohm: 3.65,
    avg_capacity_pct_of_nominal: 62.6,
  },
  {
    manufacturer_id: 4,
    manufacturer_name: "BYD FinDreams Battery",
    battery_count: 3,
    avg_cycles: 396,
    avg_resistance_mohm: 1.36,
    avg_capacity_pct_of_nominal: 92.3,
  },
  {
    manufacturer_id: 5,
    manufacturer_name: "Samsung SDI",
    battery_count: 2,
    avg_cycles: 810,
    avg_resistance_mohm: 2.53,
    avg_capacity_pct_of_nominal: 76.1,
  },
];

export const analyticsDashboard = {
  totals: {
    batteries: 12,
    open_alerts: 4,
    active_monitoring: 12,
    avg_fleet_soh: 81.3,
    critical_packs: 1,
    high_risk_packs: 3,
  },
  batteries_by_status: [
    { status: "ACTIVE", count: 10 },
    { status: "WARNING", count: 2 },
  ],
  risk_distribution: [
    { risk_type: "THERMAL", final_risk_level: "LOW", battery_count: 6 },
    { risk_type: "THERMAL", final_risk_level: "MEDIUM", battery_count: 3 },
    { risk_type: "THERMAL", final_risk_level: "HIGH", battery_count: 2 },
    { risk_type: "THERMAL", final_risk_level: "CRITICAL", battery_count: 1 },
    { risk_type: "HEALTH", final_risk_level: "LOW", battery_count: 5 },
    { risk_type: "HEALTH", final_risk_level: "MEDIUM", battery_count: 3 },
    { risk_type: "HEALTH", final_risk_level: "HIGH", battery_count: 2 },
    { risk_type: "HEALTH", final_risk_level: "CRITICAL", battery_count: 2 },
  ],
  open_alerts_by_priority: [
    { priority_code: "CRITICAL", severity_level: 4, count: 1 },
    { priority_code: "HIGH", severity_level: 3, count: 2 },
    { priority_code: "MEDIUM", severity_level: 2, count: 1 },
  ],
};
